### ISSUE TITLE
Functions to colour strings instead of using raw ANSI scape character sequencies

### ISSUE THREAD

**Issue by Pyzyryab** [zerodaycode/Zero#23]
In the test suite, we're using ANSI scape character codes to give colour to certain kind of messages.
Since it's fine for the beginning, quickly becomes unscalable, hard to read and ugly.

I propose the creation of small functions in the `Text` module, that allows us to use C++ code instead of hardcoding the colours directly in the strings.

This can be done in any way that you want (talking to the implementor), just respect the code conventions used until know.

Note that `std::format` is available since C++20, but non available in all the major compilers, and depends on the version. And since `std::print` is coming in C++23, I am not sure if we must waste time on make a format library. But, as I said, this is still compiler dependent, and I see no features to colour text, so it could be a viable option given how `Zero` is designed (make everything that we can by ourselves).

So, if you, future implementor, thinks that is a good option, go ahead, and create a format library, that is able as well to make coloured text.

**Comment by gbm25** [comment]
Hi there,

As we've already discussed over Discord, I've made some headway on the issue you've opened. I wanted to summarize our conversation here for the sake of tracking progress and keeping everyone in the loop. Here's what I've been working on:

- Color and Text Modification: As we've talked about, I've implemented a feature that allows for modification of both the color and the style of the text. This includes options for making text bold, italic, and so on, as well as changing the color of the text. These features are bundled in the same function for seamless use.

- Format: I've also put together a basic formatter. It's a simple solution that we can utilize while we wait for other options to be fully supported by all compilers. As we've discussed, it's not a complete solution, but it should serve as a good starting point. We can continue to expand upon this formatter as needed and address any bugs that may surface.

I look forward to our next discussion on Discord to further refine these features. After our conversation, I'll make sure to post an update here to keep track of our progress.

**Comment by gbm25** [comment]
After our Discord chat, here's a quick update:

I'm glad you'll be reviewing the code. As we agreed, we'll add tests once the new suite is ready. We've also noted the Zork bugs that need addressing.

I'll provide another update after our next discussion if needed.
