### ISSUE TITLE
Implement mathematical unicode characters

### ISSUE THREAD

**Issue by Pyzyryab** [zerodaycode/Zero#29]
Is requested to implement the some of the most important mathematical unicode characters. I won't provide a full list here, but this will be some of the most important to take in consideration:

- [ ] Plus = 0x002B,                 // +
- [ ] Minus = 0x2212,                // -
- [ ] Multiply = 0x00D7,             // ×
- [ ] Divide = 0x00F7,               // ÷

- [ ] SquareRoot = 0x221A,           // √
- [ ] CubeRoot = 0x221B,             // ∛
- [ ] FourthRoot = 0x221C,           // ∜
- [ ] NthRoot = 0x221D,              // ∝ (Generic n-th root symbol)

- [ ] Summation = 0x2211,            // ∑
- [ ] Integral = 0x222B,             // ∫
- [ ] DoubleIntegral = 0x222C,       // ∬
- [ ] TripleIntegral = 0x222D,       // ∭
- [ ] ContourIntegral = 0x222E,      // ∮
- [ ] SurfaceIntegral = 0x222F,      // ∯
- [ ] VolumeIntegral = 0x2230,       // ∰

- [ ] ProportionalTo = 0x221D,       // ∝
- [ ] LessThanOrEqual = 0x2264,      // ≤
- [ ] GreaterThanOrEqual = 0x2265,   // ≥
- [ ] NotEqual = 0x2260,             // ≠
- [ ] ApproximatelyEqual = 0x2248,   // ≈

- [ ] Subset = 0x2286,               // ⊆
- [ ] Superset = 0x2287,             // ⊇
- [ ] ElementOf = 0x2208,            // ∈
- [ ] EmptySet = 0x2205,             // ∅

- [ ] LogicalAnd = 0x2227,           // ∧
- [ ] LogicalOr = 0x2228,            // ∨
- [ ] LogicalNot = 0x00AC,           // ¬

- [ ] PlusMinus = 0x00B1,           // ±
- [ ] Equal = 0x003D,               // =
- [ ] LessThan = 0x003C,            // <
- [ ] GreaterThan = 0x003E,         // >
- [ ] Infinity = 0x221E,            // ∞
- [ ] MinusInfinity = 0x2212,       // -∞

- [ ] Therefore = 0x2234,           // ∴
- [ ] Because = 0x2235,             // ∵
- [ ] Intersection = 0x2229,        // ∩
- [ ] Union = 0x222A,               // ∪

- [ ] Degree = 0x00B0,              // °
- [ ] Pi = 0x03C0,                 // π
- [ ] Sigma = 0x03A3,              // Σ
- [ ] Delta = 0x2206,              // ∆
- [ ] Alpha = 0x03B1,              // α
- [ ] Beta = 0x03B2,               // β
- [ ] Gamma = 0x03B3,              // γ
- [ ] Epsilon = 0x03B5,           // ε
- [ ] Zeta = 0x03B6,              // ζ
- [ ] Eta = 0x03B7,               // η
- [ ] Mu = 0x03BC,                // μ
- [ ] Nu = 0x03BD,                // ν
- [ ] Xi = 0x039E,                // Ξ
- [ ] Rho = 0x03C1,               // ρ
- [ ] Tau = 0x03C4,               // τ
- [ ] Phi = 0x03A6,               // Φ
- [ ] Psi = 0x03A8,               // Ψ
- [ ] Omega = 0x03A9,             // Ω

- [ ] NaturalNumbers = 0x2115,    // ℕ
- [ ] Integers = 0x2124,          // ℤ
- [ ] Rationals = 0x211A,         // ℚ
- [ ] Reals = 0x211D,             // ℝ
- [ ] ComplexNumbers = 0x2102,   // ℂ

- [ ] Aleph = 0x2135,              // ℵ
- [ ] OpenParenthesis = 0x0028,   // (
- [ ] CloseParenthesis = 0x0029,  // )

- [ ] Exists = 0x2203,             // ∃ (Exists)
- [ ] ForAll = 0x2200,             // ∀ (For All)

- [ ] ElementOf = 0x2208,          // ∈
- [ ] EmptySet2 = 0x2205,         // ∅ (Empty Set)
- [ ] OpenCurlyBrace2 = 0x007B,   // {
- [ ] CloseCurlyBrace2 = 0x007D,  // }
- [ ] ApproximatelyEqual2 = 0x2245, // ≅ (Approximately Equal)
- [ ] LogicalAnd2 = 0x2227,      // ∧
- [ ] LogicalOr2 = 0x2228,       // ∨
- [ ] ElementOf3 = 0x2208,        // ∈
- [ ] PlusMinus2 = 0x00B1,       // ±
- [ ] DivisionSlash = 0x2044,   // ⁄ (Division Slash)
- [ ] SquareRoot3 = 0x221A,      // √
- [ ] Integral2 = 0x222E,       // ∮ (Contour Integral)
- [ ] ElementOfOrEqual = 0x220B, // ∋ (Contains or Equal)
- [ ] OpenSquareBrace = 0x005B,  // [
- [ ] CloseSquareBrace = 0x005D, // ]

- [ ] Superscript1 = 0x00B9,       // ¹ (Superscript 1)
- [ ] Superscript2 = 0x00B2,       // ² (Superscript 2)
- [ ] Superscript3 = 0x00B3,       // ³ (Superscript 3)
- [ ] SuperscriptPlus = 0x207A,    // ⁺ (Superscript Plus)
- [ ] SuperscriptMinus = 0x207B,   // ⁻ (Superscript Minus)
- [ ] Subscript1 = 0x2081,         // ₁ (Subscript 1)
- [ ] Subscript2 = 0x2082,         // ₂ (Subscript 2)
- [ ] Subscript3 = 0x2083,         // ₃ (Subscript 3)

- [ ] PartialDerivative = 0x2202,  // ∂ (Partial Derivative)
- [ ] Nabla = 0x2207,              // ∇ (Nabla)
- [ ] Gradient = 0x2207,           // ∇ (Gradient)
- [ ] DelSquared = 0x2207,         // ∇² (Del Squared)
- [ ] VectorDiv = 0x2207,          // ∇ · (Divergence)
- [ ] Laplace = 0x2207,            // ∇² (Laplace Operator)

- [ ] VectorArrow = 0x2192,        // → (Vector Arrow)
- [ ] CrossProduct = 0x00D7,       // × (Cross Product)
- [ ] DotProduct = 0x22C5,         // ⋅ (Dot Product)

- [ ] Matrix = 0x23A0,             // ⎠ (Matrix)
- [ ] MatrixTranspose = 0x22A4,    // ⊤ (Matrix Transpose)
- [ ] MatrixHermitian = 0x22B2,    // ⊲ (Matrix Hermitian)

- [ ] Power = 0x207F,              // ⁿ (Superscript n)
- [ ] EmptySet3 = 0x2205,         // ∅ (Empty Set)
- [ ] OpenAngleBrace = 0x2329,     // 〈
- [ ] CloseAngleBrace = 0x232A,    // 〉

There are somethings that we should talk about, like the way on how we can implement any superscript (x0x207F -> this means, x raised to the n-th power, being n some number that belongs from naturals to complex numbers) without having to hardcoding one by one, so probably an enum won't be enough here, and we will need to implement a more sophisticated implementation, or maybe split into the ones that are just symbols than the ones that are combinations, like in the past example :)

**Comment by gbm25** [comment]
I close the issue since we have already merged the code that solves the issue
